## <img src="https://raw.githubusercontent.com/alexnaiman/alexnaiman/master/resources/welcomeglitch.gif" width="50px" /> Hello!

< p align="center" >
  <samp>
    My name is <em>Zoey Zuo</em>. My MBTI is INFP... 
  <br/> I'm Girl... And I have a beautiful girl. Her Name is Lao JiaYing. 
    <br/> (<em>- -</em>) I Really Love Her.
      <br/>
I like watching movies,
          <br/>
traveling and playing games
  </samp>
  <br/>
  <br/>
  <br/>
</p>

<img src="https://media.tenor.com/images/df8c44a1d20ab367fdcb21880985fd33/tenor.gif" align="right"  width="30%" alt=""/>

### <img src="https://raw.githubusercontent.com/alexnaiman/alexnaiman/master/resources/PusheenCompute.gif" width="70px" />  I'm studying for a postgraduate degree in Lingnan ...

-    I major in MSCCT+
-    I  chose the computer direction

### <img src="https://raw.githubusercontent.com/alexnaiman/alexnaiman/master/resources/Confused_Dog.gif" height="50px" /> I’m currently learning these languages...

-  Japanese
-  Cantonese
-  French
-  English

### <img src="https://raw.githubusercontent.com/alexnaiman/alexnaiman/master/resources/pug_dance.gif" width="60px" /> I want to travel to these countries ...

- <img src="https://raw.githubusercontent.com/alexnaiman/alexnaiman/master/resources/open_source.png" height="30px"  alt=""/> Japan, England, New Zealand...

### <img src="https://raw.githubusercontent.com/alexnaiman/alexnaiman/master/resources/cool_duck.gif" width="60px" /> I’m looking for help with ...

- <img src="https://raw.githubusercontent.com/alexnaiman/alexnaiman/master/resources/party_parrot.gif" height="35px"  alt=""/> any weird or interesting idea

### <img src="https://raw.githubusercontent.com/alexnaiman/alexnaiman/master/resources/question.png" width="50px" />  Ask me about ...

- <img src="https://raw.githubusercontent.com/alexnaiman/alexnaiman/master/resources/chat.gif" height="35px"  alt=""/> anything, I am really a talkative person, happy to help 

### <img src="https://raw.githubusercontent.com/alexnaiman/alexnaiman/master/resources/bongocat.gif" width="50px" /> How to reach me: ...

<p align="center">
  <a href="https://twitter.com/naiman_alex">
  <a href="https://www.instagram.com/alex.naiman.4/">
    <img src="https://raw.githubusercontent.com/alexnaiman/alexnaiman/master/resources/instagram.webp" height="35px" style="margin: 5px;"  alt=""/>
  </a>
